// <auto-generated />
using System;
using ASP.NET_CoreTicTacToe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_CoreTicTacToe.Migrations
{
    [DbContext(typeof(TicTacToeContext))]
    [Migration("20200120134245_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_CoreTicTacToe.Models.Board", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("ASP.NET_CoreTicTacToe.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("BoardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HistoryID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("BoardID");

                    b.HasIndex("HistoryID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ASP.NET_CoreTicTacToe.Models.History", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("History");
                });

            modelBuilder.Entity("ASP.NET_CoreTicTacToe.Models.Turn", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("HistoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WhichTurn")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HistoryID");

                    b.ToTable("Turn");
                });

            modelBuilder.Entity("ASP.NET_CoreTicTacToe.Models.Game", b =>
                {
                    b.HasOne("ASP.NET_CoreTicTacToe.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardID");

                    b.HasOne("ASP.NET_CoreTicTacToe.Models.History", "History")
                        .WithMany()
                        .HasForeignKey("HistoryID");
                });

            modelBuilder.Entity("ASP.NET_CoreTicTacToe.Models.Turn", b =>
                {
                    b.HasOne("ASP.NET_CoreTicTacToe.Models.History", null)
                        .WithMany("Turns")
                        .HasForeignKey("HistoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
