//Action Type
export const ALL_GAMES_RECEIVED = 'ALL_GAMES_RECEIVED'
export const GAME_INIT = 'GAME_INIT';
export const LOBBY_INIT = 'LOBBY_INIT';
export const PLAYER_NAMES_RECEIVED = 'PLAYER_NAMES_RECEIVED';
export const SIDE_RECEIVED = 'SIDE_RECEIVED';
export const SPECTATOR_RESOLVED = 'SPECTATOR_RESOLVED';