export const HISTORY_BUTTON_SWITCHED = 'HISTORY_BUTTON_SWITCHED';
export const HISTORY_INIT = 'HISTORY_INIT';
export const HISTORY_ITEM_ADDED = 'HISTORY_ITEM_ADDED';
export const HISTORY_ITEM_CLICKED = 'HISTORY_ITEM_CLICKED';
export const HISTORY_REQUESTED = 'HISTORY_REQUESTED';